dynamic_background_opacity yes 
background_opacity 0.7
#background_tint 0.9 
allow_remote_control yes
map ctrl+shift+comma previous_tab
map ctrl+shift+period next_tab
map ctrl+shift+left  move_tab_backward
map ctrl+shift+right move_tab_forward
