dynamic_background_opacity yes 
background_opacity 0.7
#background_tint 0.9 
allow_remote_control yes
map ctrl+shift+j previous_tab
map ctrl+shift+k next_tab
map super+shift+left  move_tab_backward
map super+shift+right move_tab_forward
map ctrl+c copy_to_clipboard
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text all \x03
map ctrl+shift+d send_text all \x04
#map ctrl+shift+, no_op
#map ctrl+shift+. no_op
scrollback_lines 100000
#map ctrl+shift+a launch --stdin-source=@screen_scrollback xsel --clipboard --input
map ctrl+backspace send_text all \x17
