dynamic_background_opacity yes 
background_opacity 0.7
#background_tint 0.9 
allow_remote_control yes
map super+shift+comma previous_tab
map super+shift+period next_tab
map super+shift+left  move_tab_backward
map super+shift+right move_tab_forward
map ctrl+shift+, no_op
map ctrl+shift+. no_op
scrollback_lines 100000
#map ctrl+shift+a launch --stdin-source=@screen_scrollback xsel --clipboard --input
map ctrl+backspace send_text all \x17
